@startuml container
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(user, "Traveler")
Container(lb, "Load Balancer", "HTTPS, round-robin")

System(webapp, "Web UI")

Container(gateway, "Gateway", "go", "Auth, Rate limit, cache, proxy etc.")
ContainerDb(gateway_db, "TokenBucket", "Redis")
Container(auth, "Auth", "go", "session-based")
ContainerDb(auth_db, "DB", "Redis")
ContainerDb(users_db, "DB", "Postgres")
Container(images, "Images", "go")
ContainerDb(images_db, "DB", "MongoDB")
ContainerDb(images_blob, "Blob", "S3")
Container(posts, "Posts", "go")
ContainerDb(posts_db, "DB", "MongoDB")
Container(locations, "Locations", "go")
ContainerDb(locations_db, "DB", "Neo4j")
Container(comments, "Comments", "go")
ContainerDb(comments_db, "DB", "MongoDB")
Container(follow, "Follows", "go")
Container(follow_db, "DB", "Neo4j")
Container(feed, "Feed", "go")
ContainerDb(feed_db, "DB", "KV")
Container(users, "Users", "go")
Container(api, "API", "go", "business logic")
ContainerQueue(post_create_topic, "Post Create Topic", "kafka")

Container_Ext(cdn, "CDN")

Rel(user, lb, "HTTPS")
Rel(user, cdn, "static, media")
Rel(lb, webapp, "Interract with travelers, posts, comments, etc.")
Rel(webapp, gateway, "HTTPS, Rest API")
Rel_R(gateway, auth, "sign-in, sign-out etc", "gRPC")
Rel(gateway, gateway_db, "limits")
Rel(gateway, api, "", "gRPC")
Rel(api, users, "CRUD", "gRPC")
Rel(api, follow, "CRUD", "gRPC")
Rel(api, posts, "CRUD", "gRPC")
Rel(api, feed, "CRUD", "gRPC")
Rel(api, images, "CRUD", "gRPC")
Rel(api, locations, "CRUD", "gRPC")
Rel(api, comments, "CRUD", "gRPC")
Rel(auth, auth_db, "store sessions")
Rel(images, images_db, "store metadata")
Rel(images, images_blob, "store blob")
Rel(cdn, images_blob, "pull")
Rel(posts, posts_db, "store")
Rel(posts, post_create_topic, "push")
Rel(locations, locations_db, "store")
Rel(comments, comments_db, "store")
Rel(follow, follow_db, "store")
Rel(users, users_db, "store")
Rel(feed, feed_db, "store")
Rel(feed, post_create_topic, "pull")
Rel_R(feed, follow, "CRUD", "gRPC")
Rel_L(feed, posts, "CRUD", "gRPC")

@enduml